feat: update works, added yay migratino

diff --git a/saurh b/saurh
--- a/saurh
+++ b/saurh
@@ -18,7 +18,7 @@ remove, remove"
 exit 1
 fi
 
-if [[ $1 == "install" ]]
+if [ $1 == "install" ];
 then 
 	if [[ -z $2 ]]
 	then
@@ -50,7 +50,7 @@ then
 	makepkg -si || echo "There was a problem when installing this package, drop into ~/.local/share/saurh/package and try to makepkg or fix issues yourself."
 fi
 
-if [[ $1 == "uninstall" ]]
+if [ $1 == "uninstall" ];
 then	command -v pacman >&/dev/null || exit 1
 	if [[ -v $2 ]]
 	then
@@ -59,12 +59,29 @@ then	command -v pacman >&/dev/null || exit 1
 	sudo pacman -R $2 || echo "command failed, is the package not installed?"
 fi
 
+if [ $1 == "yay-migrate" ];
+then
+	echo Migrating build files from yay cache...
+	file="$HOME/.cache/yay/"
+	if [ ! -d "$file" ]; then
+		echo "ERR: No yay cache to migrate"
+		exit
+	fi
+	cp -r $HOME/.cache/yay/* $HOME/.cache/saurh/
+fi
+
+
 if [[ $1 == "update" ]]
 then
-	find $HOME/.local/share/saurh/ -mindepth 1 -maxdepth 1 -type d | while read pkg; do
-		cd $pkg
-		git pull
-		makepkg -si || echo "There was a problem when installing this package, drop into ~/.local/share/saurh/package-name and try to makepkg or fix issues yourself."
+	find $HOME/.cache/saurh -mindepth 1 -maxdepth 1 -type d | while read pkg; do
+	cd $pkg
+	if [[ `git status --porcelain --untracked-files=no` ]]; then
+  		echo Updates available for package $pkg
+	else
+  		echo No updates available for package $pkg
+		exit
+fi
+		makepkg -si || echo "ERR: Failed to install package $pkg"
 	done
 fi
 
